# Generated by Django 5.2.12 on 2026-04-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
