# Generated by Django 5.2.12 on 2026-04-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='aes_iv',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='aes_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='encrypted_cf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='seal_image',
            field=models.ImageField(blank=True, null=True, upload_to='seals/'),
        ),
    ]
