# Generated by Django 5.2.12 on 2026-04-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_aes_iv_contract_aes_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hmac_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='wrapped_key',
            field=models.TextField(blank=True),
        ),
    ]
