# Generated by Django 5.2.12 on 2026-05-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_hmac_value_contract_wrapped_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='original_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
