# Generated by Django 5.2.16 on 2026-07-10 00:48

import contracts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_modified_at_contract_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(['pdf']), contracts.models.validate_pdf_signature]),
        ),
    ]
