# Generated by Django 5.2.16 on 2026-07-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Draft'), ('sent', 'Sent'), ('approved', 'Signed')], default='pending', max_length=20),
        ),
    ]
