# Generated by Django 5.2.16 on 2026-08-26 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_folder_contract_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('upload', 'Initial Upload'), ('reencrypt', 'Re-encryption'), ('physical_scan', 'Physical Signature Scan')], max_length=20)),
                ('file', models.FileField(upload_to='contract_versions/')),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('previous_fingerprint', models.CharField(blank=True, max_length=64)),
                ('encrypted_cf', models.TextField(blank=True)),
                ('hmac_value', models.TextField(blank=True)),
                ('wrapped_key', models.TextField(blank=True)),
                ('aes_iv', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('contract', 'version_number')},
            },
        ),
    ]
