# Generated by Django 5.2.16 on 2026-08-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_contractversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contractversion',
            name='source',
            field=models.CharField(choices=[('upload', 'Initial Upload'), ('revision', 'New Revision Upload'), ('reencrypt', 'Re-encryption'), ('physical_scan', 'Physical Signature Scan')], max_length=20),
        ),
    ]
