# Generated by Django 5.2.16 on 2026-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_contract_is_public_alter_contractversion_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='base_filename',
            field=models.CharField(blank=True, help_text='Original filename (no extension), reused across versions', max_length=200),
        ),
    ]
