# Generated by Django 5.2.16 on 2026-08-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_contract_base_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
