# Generated by Django 4.2 on 2026-09-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_add_inline_tutorial_icons'),
        ('contracts', '0022_auditlog_verification_details'),
    ]

    operations = [
    ]
