# Generated by Django 4.2 on 2026-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_merge_20260902_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='icon',
            field=models.CharField(choices=[('help', 'Help'), ('shield', 'Shield'), ('file', 'Document'), ('upload', 'Upload'), ('lock', 'Encryption'), ('search', 'Search'), ('folder', 'Folder'), ('dashboard', 'Dashboard'), ('eye', 'View'), ('download', 'Download'), ('history', 'History'), ('warning', 'Warning'), ('check', 'Check'), ('user', 'User'), ('plus', 'Add'), ('trash', 'Trash'), ('restore', 'Restore')], default='help', max_length=20),
        ),
    ]
