# Generated by Django 4.2 on 2026-09-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_auditlog_downloaded_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='version_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
