# Generated by Django 4.2 on 2026-09-16 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0036_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
