# Generated by Django 4.2 on 2026-09-16 23:52

import contracts.models
import contracts.pdf_storage
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0044_expanded_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, storage=contracts.pdf_storage.EncryptedPDFStorage(), upload_to='verification_evidence/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(storage=contracts.pdf_storage.EncryptedPDFStorage(), upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(['pdf']), contracts.models.validate_pdf_signature]),
        ),
        migrations.AlterField(
            model_name='contractversion',
            name='file',
            field=models.FileField(storage=contracts.pdf_storage.EncryptedPDFStorage(), upload_to='contract_versions/'),
        ),
        migrations.CreateModel(
            name='DocumentAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('reason', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('email_pending', 'Verify email'), ('pending', 'Awaiting staff approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='email_pending', max_length=20)),
                ('otp_hash', models.CharField(blank=True, max_length=128)),
                ('otp_expires_at', models.DateTimeField()),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_file', models.CharField(blank=True, max_length=255)),
                ('approved_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contractversion')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='contracts.documentaccesslink')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentaccesslink',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_link', to='contracts.contract'),
        ),
    ]
