# Generated by Django 4.2 on 2026-09-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0046_contract_final_copy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccesslink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentaccesslink',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentaccesslink',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_links', to='contracts.contract'),
        ),
    ]
