from django.urls import path
from . import views

urlpatterns = [
    path('verify/', views.public_verify, name='public_verify'),
    path('verify/preview/<str:token>/', views.verification_preview, name='verification_preview'),
    path('dashboard/activity/<int:log_id>/preview/', views.audit_evidence_preview, name='audit_evidence_preview'),
    path('dashboard/activity/<int:log_id>/verification-history/', views.audit_verification_history, name='audit_verification_history'),
    path('dashboard/activity/<int:log_id>/verification-log/', views.audit_verification_log_detail, name='audit_verification_log_detail'),
    path('contracts/', views.contract_list, name='contract_list'),
    path('upload/', views.upload_contract, name='upload_contract'),
    path('upload/check-duplicate/', views.check_duplicate_upload, name='check_duplicate_upload'),
    path('encrypt/<int:contract_id>/', views.encrypt_contract, name='encrypt_contract'),
    path('delete/<int:contract_id>/', views.delete_contract, name='delete_contract'),
    path('delete/bulk/', views.bulk_delete_contracts, name='bulk_delete_contracts'),
    path('contracts/bulk/folder/', views.bulk_assign_folder, name='bulk_assign_folder'),
    path('contracts/bulk/status/', views.bulk_update_status, name='bulk_update_status'),
    path('contracts/bulk/encrypt/', views.bulk_encrypt_contracts, name='bulk_encrypt_contracts'),
    path('contracts/bulk/download/', views.bulk_download_contracts, name='bulk_download_contracts'),
    path('verify/physical/', views.verify_physical, name='verify_physical'),
    path('verify/physical/check-qr/', views.verify_physical_qr, name='verify_physical_qr'),
    path('verify/physical/review/<int:log_id>/<int:version_id>/', views.physical_verification_review, name='physical_verification_review'),
    path('rename/<int:pk>/', views.rename_contract, name='rename_contract'),
    path('status/<int:pk>/',  views.update_status,   name='update_status'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/export/', views.export_dashboard_report, name='export_dashboard_report'),
    path('help/', views.help_tutorials, name='help_tutorials'),
    path('help/<int:pk>/edit/', views.edit_tutorial, name='edit_tutorial'),
    path('help/<int:pk>/delete/', views.delete_tutorial, name='delete_tutorial'),
    path('tag/<int:pk>/', views.tag_contract, name='tag_contract'),
    path('folder/create/', views.create_folder, name='create_folder'),
    path('folder/reorder/', views.reorder_folders, name='reorder_folders'),
    path('folder/rename/<int:pk>/', views.rename_folder, name='rename_folder'),
    path('folder/assign/<int:contract_id>/', views.assign_folder, name='assign_folder'),
    path('folder/delete/<int:pk>/', views.delete_folder, name='delete_folder'),
    path('contract/<int:contract_id>/upload-signed/', views.upload_signed_scan, name='upload_signed_scan'),
    path('contract/<int:contract_id>/add-revision/', views.add_revision, name='add_revision'),
    path('contract/<int:pk>/publish/', views.publish_contract, name='publish_contract'),
    path('contract/<int:contract_id>/version-history/', views.contract_version_history, name='contract_version_history'),
    path('contract/<int:contract_id>/download/', views.download_contract, name='download_contract'),
    path('contract/version/<int:version_id>/download/', views.download_contract_version, name='download_contract_version'),
    path('contract/<int:contract_id>/preview/', views.preview_contract, name='preview_contract'),
    path('contract/version/<int:version_id>/preview/', views.preview_contract_version, name='preview_contract_version'),
    path('contract/<int:contract_id>/mark-viewed/', views.mark_contract_viewed, name='mark_contract_viewed'),
    path('trash/', views.trash_list, name='trash_list'),
    path('trash/restore/<int:contract_id>/', views.restore_contract, name='restore_contract'),
    path('trash/delete-forever/<int:contract_id>/', views.permanently_delete_contract, name='permanently_delete_contract'),
    path('trash/delete-forever/bulk/', views.bulk_permanently_delete_contracts, name='bulk_permanently_delete_contracts'),
    path('trash/empty/', views.empty_trash, name='empty_trash'),
]

